#!/usr/bin/env python3
"""sync_agents.py - generate OpenCode agent files from canonical Claude Code agents.

Part of the opencode-sync skill. Deterministic, stdlib only (no PyYAML - it is
not guaranteed on the system Python path, so a minimal frontmatter parser is
used instead).

What it does:
  1. Parses the YAML frontmatter of one or more Claude Code agent .md files
     using a minimal hand-rolled parser (key: value, dash lists, block scalars).
  2. Maps fields to OpenCode agent frontmatter:
       description (required)  -> description
       name / filename         -> output filename (OpenCode names agents by file)
       model alias             -> provider/model-id (see MODEL_ALIASES / model_map)
       temperature             -> temperature (passthrough, 0-1)
       tools (allowlist)       -> tools boolean map (listed true, other builtins false)
       mode                    -> from --mode flag or config (default: subagent)
  3. Translates tool names (Read -> read, AskUserQuestion -> question, ...),
     degrades Task* to todowrite/todoread, drops tools with no equivalent, and
     records every degradation as a warning.
  4. Writes <out-dir>/<name>.md with a GENERATED header and an optional Runtime
     notes block, and records source/generated sha256 pairs in the sync manifest
     for check_drift.py.

Two ways to run:
  Config-driven (the way the SKILL.md Mode B drives it):
    python3 sync_agents.py --config .opencode-sync/config.json [--dry-run] [--strict]
  Direct:
    python3 sync_agents.py path/to/agent.md [more.md ...] \
        [--out-dir .opencode/agent] [--mode subagent|primary|all] \
        [--provider anthropic] [--manifest .opencode-sync/manifest.json] \
        [--model-map model_map.json] [--no-annotate] [--dry-run] [--strict]

Exit codes: 0 ok | 1 parse or write failure | 2 warnings under --strict
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Mapping tables - keep in sync with references/tool-translation.md and
# references/field-mapping.md. Verify the builtin list and model IDs against
# https://opencode.ai/docs/tools and https://models.dev before a big run -
# OpenCode releases roughly fortnightly and these move.
# ---------------------------------------------------------------------------

# Claude Code tool name -> OpenCode tool name (direct equivalents)
TOOL_MAP = {
    "Read": "read",
    "Write": "write",
    "Edit": "edit",
    "Bash": "bash",
    "Glob": "glob",
    "Grep": "grep",
    "WebFetch": "webfetch",
    "WebSearch": "websearch",
    "TodoWrite": "todowrite",
    "Task": "task",
    "Agent": "task",
    "Skill": "skill",
    "AskUserQuestion": "question",
}

# Claude tools that DEGRADE on OpenCode: mapped, but semantics are weaker.
# Task* loses addBlockedBy dependency chains - it becomes a flat checklist.
DEGRADED_MAP = {
    "TaskCreate": ["todowrite"],
    "TaskUpdate": ["todowrite"],
    "TaskGet": ["todoread"],
    "TaskList": ["todoread"],
}

# Claude tools with NO OpenCode equivalent - dropped with a warning.
DROPPED = {
    "SendMessage",
    "ScheduleWakeup",
    "EnterPlanMode",
    "ExitPlanMode",
    "EnterWorktree",
    "ExitWorktree",
    "NotebookEdit",
    "KillShell",
    "ToolSearch",  # OpenCode loads all tools up front; no deferred schema search
    "TaskOutput",  # background-subagent monitor; no OpenCode equivalent
    "TaskStop",    # background-subagent monitor; no OpenCode equivalent
}

# OpenCode builtin tool names (Jun 2026). When a Claude agent has an allowlist,
# faithful translation enables the mapped tools and disables the rest of these.
OPENCODE_BUILTINS = [
    "bash", "edit", "write", "read", "grep", "glob", "list",
    "skill", "todowrite", "todoread", "webfetch", "websearch",
    "question", "task", "apply_patch",
]

# Claude model aliases / short ids -> OpenCode provider/model-id.
# VERIFY against models.dev - these go stale. Override with --model-map or config.
MODEL_ALIASES = {
    "sonnet": "anthropic/claude-sonnet-4-5",
    "opus": "anthropic/claude-opus-4-1",
    "haiku": "anthropic/claude-haiku-4-5",
    "inherit": None,  # omit -> OpenCode inherits the session model
}

GENERATED_MARKER = "GENERATED by opencode-sync"

# ---------------------------------------------------------------------------
# Minimal frontmatter parser. Handles the subset agents actually use:
#   key: value            (plain scalars, quoted strings)
#   key:                  (followed by "  - item" dash lists)
#   key: >- / > / | / |-  (block scalars, indented continuation lines)
# Anything fancier should go through a real YAML library on a machine that
# has one. Unknown structures are kept as raw strings.
# ---------------------------------------------------------------------------


def split_frontmatter(text):
    """Return (frontmatter_lines, body) or (None, text) if no frontmatter."""
    if not text.startswith("---"):
        return None, text
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, re.DOTALL)
    if not m:
        return None, text
    return m.group(1).split("\n"), text[m.end():]


def parse_frontmatter(lines):
    """Parse the supported YAML subset into a dict. Lists -> list, rest -> str."""
    data = {}
    i = 0
    key_re = re.compile(r"^([A-Za-z0-9_-]+):\s*(.*)$")
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        m = key_re.match(line)
        if not m:
            i += 1  # continuation of something we did not model; skip
            continue
        key, rest = m.group(1), m.group(2).rstrip()
        if rest in (">", ">-", "|", "|-", ">+", "|+"):
            block, i = _consume_block(lines, i + 1)
            data[key] = " ".join(block) if rest.startswith(">") else "\n".join(block)
        elif rest == "":
            items, i = _consume_list(lines, i + 1)
            data[key] = items if items is not None else ""
            continue  # _consume_list already advanced i
        else:
            data[key] = _unquote(rest)
            i += 1
            continue
        i += 1
    return data


def _consume_block(lines, start):
    block = []
    i = start
    while i < len(lines) and (lines[i].startswith("  ") or not lines[i].strip()):
        block.append(lines[i].strip())
        i += 1
    return [b for b in block if b], i - 1


def _consume_list(lines, start):
    items = []
    i = start
    while i < len(lines):
        s = lines[i]
        if re.match(r"^\s+-\s+", s):
            items.append(_unquote(re.sub(r"^\s+-\s+", "", s).strip()))
            i += 1
        elif not s.strip():
            i += 1
        else:
            break
    return (items if items else None), i


def _unquote(value):
    v = value.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        return v[1:-1]
    return v


def coerce_tools(raw):
    """tools can be a dash list or an inline comma string - normalise to a list."""
    if raw is None:
        return None
    if isinstance(raw, list):
        return [t.strip() for t in raw if t.strip()]
    s = str(raw).strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1]
    return [t.strip() for t in s.split(",") if t.strip()]


# ---------------------------------------------------------------------------
# Conversion
# ---------------------------------------------------------------------------


def map_model(model, provider, aliases):
    if not model:
        return None, None
    m = str(model).strip()
    if m in aliases:
        mapped = aliases[m]
        warn = None if mapped else f"model '{m}' maps to inherit - omitted"
        return mapped, warn
    if "/" in m:
        return m, None
    return f"{provider}/{m}", (
        f"model '{m}' not in model map - assumed '{provider}/{m}', TODO-VERIFY on models.dev"
    )


def convert_tools(tool_list):
    """Return (enabled set of opencode names, warnings list, mcp passthroughs)."""
    enabled, warnings, mcp = set(), [], []
    for t in tool_list:
        if t in TOOL_MAP:
            enabled.add(TOOL_MAP[t])
        elif t in DEGRADED_MAP:
            for oc in DEGRADED_MAP[t]:
                enabled.add(oc)
            warnings.append(
                f"{t} degraded to {'/'.join(DEGRADED_MAP[t])} - dependency chains (addBlockedBy) are lost on OpenCode"
            )
        elif t in DROPPED:
            warnings.append(f"{t} has no OpenCode equivalent - dropped")
        elif t.startswith("mcp__"):
            mcp.append(t)
        else:
            warnings.append(f"unknown tool '{t}' - dropped (add it to TOOL_MAP if it has an equivalent)")
    if mcp:
        warnings.append(
            "MCP tools not written to the tools map (OpenCode names them per server config): "
            + ", ".join(mcp)
        )
    return enabled, warnings, mcp


def build_output(source_path, fm, body, args):
    name = (fm.get("name") or source_path.stem).strip()
    description = fm.get("description", "").strip()
    warnings = []
    if not description:
        warnings.append("description missing - OpenCode REQUIRES description; inserted a placeholder (E4)")
        description = f"Converted from {source_path.name}. TODO: write a real description."

    model, model_warn = map_model(fm.get("model"), args.provider, args.model_aliases)
    if model_warn:
        warnings.append(model_warn)

    tool_list = coerce_tools(fm.get("tools"))
    tools_block_lines = []
    if tool_list:
        enabled, tool_warnings, _mcp = convert_tools(tool_list)
        warnings.extend(tool_warnings)
        tools_block_lines.append("tools:")
        for oc in OPENCODE_BUILTINS:
            tools_block_lines.append(f"  {oc}: {'true' if oc in enabled else 'false'}")

    out = ["---", f"description: {_yaml_str(description)}", f"mode: {args.mode}"]
    if model:
        out.append(f"model: {model}")
    temp = fm.get("temperature")
    if temp:
        out.append(f"temperature: {temp}")
    out.extend(tools_block_lines)
    out.append("---")

    src_sha = sha256_file(source_path)
    out.append("")
    out.append(
        f"<!-- {GENERATED_MARKER} from {source_path.as_posix()} "
        f"(source sha256 {src_sha[:12]}) on {_now()}. "
        f"Do not edit by hand - edit the canonical source and re-run sync_agents.py. -->"
    )

    if args.annotate and warnings:
        out.append("")
        out.append("> **Runtime notes (OpenCode)** - generated by opencode-sync:")
        for w in warnings:
            out.append(f"> - {w}")

    out.append("")
    out.append(body.strip())
    out.append("")
    return name, "\n".join(out), warnings, src_sha


def _yaml_str(s):
    s = " ".join(s.split())
    if any(c in s for c in ":#{}[]&*!|>'\"%@`"):
        return '"' + s.replace('"', '\\"') + '"'
    return s


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def sha256_file(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Manifest (consumed by check_drift.py)
# ---------------------------------------------------------------------------


def load_manifest(path):
    p = Path(path)
    if p.exists():
        try:
            return json.loads(p.read_text())
        except json.JSONDecodeError:
            print(f"WARN: manifest {p} is not valid JSON - starting fresh", file=sys.stderr)
    return {"version": 1, "generated": {}}


# ---------------------------------------------------------------------------
# Config-driven entry (Mode B). Reads .opencode-sync/config.json and expands it
# into the same arguments the direct CLI takes.
# ---------------------------------------------------------------------------


def apply_config(args):
    """Populate args.inputs / out_dir / model map / mode from a config file."""
    cfg = json.loads(Path(args.config).read_text())
    skip = set(cfg.get("skip_paths", []))
    inputs = []
    for d in cfg.get("canonical_agent_dirs", []):
        if d not in skip:
            inputs.append(d)
    if not inputs:
        print("ERROR: config has no canonical_agent_dirs to read", file=sys.stderr)
        return None
    args.inputs = inputs
    args.out_dir = cfg.get("opencode_agent_dir", args.out_dir)
    args.mode = cfg.get("default_agent_mode", args.mode)
    if cfg.get("model_map"):
        args.model_aliases.update(cfg["model_map"])
    return args


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="*", help="Claude Code agent .md files, or directories to scan")
    ap.add_argument("--config", help="read inputs/out-dir/mode/model_map from this JSON config (Mode B)")
    ap.add_argument("--out-dir", default=".opencode/agent", help="output directory (default: .opencode/agent)")
    ap.add_argument("--mode", default="subagent", choices=["subagent", "primary", "all"])
    ap.add_argument("--provider", default="anthropic", help="provider prefix for bare model ids")
    ap.add_argument("--model-map", help="JSON file overriding the model alias table")
    ap.add_argument("--manifest", default=".opencode-sync/manifest.json")
    ap.add_argument("--no-annotate", dest="annotate", action="store_false", help="omit the Runtime notes block")
    ap.add_argument("--dry-run", action="store_true", help="print what would be written, write nothing")
    ap.add_argument("--strict", action="store_true", help="exit 2 if any conversion produced warnings")
    args = ap.parse_args()

    args.model_aliases = dict(MODEL_ALIASES)
    if args.model_map:
        args.model_aliases.update(json.loads(Path(args.model_map).read_text()))

    if args.config:
        if apply_config(args) is None:
            return 1
    if not args.inputs:
        print("ERROR: no inputs (pass agent files/dirs, or --config)", file=sys.stderr)
        return 1

    files = []
    for raw in args.inputs:
        p = Path(raw)
        if p.is_dir():
            files.extend(sorted(p.glob("**/*.md")))
        elif p.is_file():
            files.append(p)
        else:
            print(f"WARN: {p} not found - skipped", file=sys.stderr)

    if not files:
        print("ERROR: no agent .md files resolved from the inputs", file=sys.stderr)
        return 1

    out_dir = Path(args.out_dir)
    manifest = load_manifest(args.manifest)
    any_warnings, failures = False, 0

    for src in files:
        text = src.read_text(encoding="utf-8", errors="replace")
        fm_lines, body = split_frontmatter(text)
        if fm_lines is None:
            print(f"SKIP {src}: no YAML frontmatter found", file=sys.stderr)
            failures += 1
            continue
        fm = parse_frontmatter(fm_lines)
        name, output, warnings, src_sha = build_output(src, fm, body, args)
        dest = out_dir / f"{name}.md"

        print(f"{src} -> {dest}" + (f"  [{len(warnings)} warning(s)]" if warnings else ""))
        for w in warnings:
            print(f"  - {w}")
        if warnings:
            any_warnings = True

        if not args.dry_run:
            out_dir.mkdir(parents=True, exist_ok=True)
            dest.write_text(output, encoding="utf-8")
            manifest["generated"][dest.as_posix()] = {
                "source": src.as_posix(),
                "source_sha256": src_sha,
                "generated_sha256": sha256_text(output),
                "generated_at": _now(),
                "warnings": warnings,
            }

    if not args.dry_run and files:
        Path(args.manifest).parent.mkdir(parents=True, exist_ok=True)
        Path(args.manifest).write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"manifest updated: {args.manifest}")

    if failures:
        return 1
    if any_warnings and args.strict:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
