#!/usr/bin/env python3
"""sync_commands.py - generate OpenCode command files from canonical Claude commands.

Part of the opencode-sync skill. Converts markdown files under `commands/` into
OpenCode command templates. The output is deterministic and stdlib-only.

What it does:
  1. Parses the YAML frontmatter of one or more Claude command .md files using a
     minimal frontmatter parser.
  2. Maps supported fields to OpenCode command frontmatter:
       description  -> description
       model        -> model (provider/model-id)
       agent        -> agent
       subtask      -> subtask
       variant      -> variant
     Unsupported fields such as `argument-hint` are dropped with a warning.
  3. Writes <out-dir>/<name>.md with a GENERATED header and records the sync in
     the shared drift manifest used by check_drift.py.

Usage:
  python3 sync_commands.py path/to/command.md [more.md ...] \
      [--out-dir .opencode/command] [--provider anthropic] \
      [--manifest .opencode-sync/manifest.json] [--model-map model_map.json] \
      [--dry-run] [--strict]

Exit codes: 0 ok | 1 parse or write failure | 2 warnings under --strict
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


MODEL_ALIASES = {
    "sonnet": "anthropic/claude-sonnet-4-5",
    "opus": "anthropic/claude-opus-4-1",
    "haiku": "anthropic/claude-haiku-4-5",
    "inherit": None,
}

GENERATED_MARKER = "GENERATED by opencode-sync"


def split_frontmatter(text):
    if not text.startswith("---"):
        return None, text
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, re.DOTALL)
    if not m:
        return None, text
    return m.group(1).split("\n"), text[m.end():]


def parse_frontmatter(lines):
    data = {}
    key_re = re.compile(r"^([A-Za-z0-9_-]+):\s*(.*)$")
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = key_re.match(line)
        if not m:
            continue
        key, rest = m.group(1), m.group(2).rstrip()
        data[key] = _unquote(rest)
    return data


def _unquote(value):
    v = value.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        return v[1:-1]
    return v


def _yaml_str(value):
    s = " ".join(str(value).split())
    if any(c in s for c in ":#{}[]&*!|>'\"%@`"):
        return '"' + s.replace('"', '\\"') + '"'
    return s


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_manifest(path):
    p = Path(path)
    if p.exists():
        try:
            return json.loads(p.read_text())
        except json.JSONDecodeError:
            print(f"WARN: manifest {p} is not valid JSON - starting fresh", file=sys.stderr)
    return {"version": 1, "generated": {}}


def map_model(model, provider, aliases):
    if not model:
        return None, None
    m = str(model).strip()
    if m in aliases:
        mapped = aliases[m]
        warn = None if mapped else f"model '{m}' maps to inherit - omitted"
        return mapped, warn
    if "/" in m:
        return m, None
    return f"{provider}/{m}", f"model '{m}' not in model map - assumed '{provider}/{m}', TODO-VERIFY on models.dev"


def build_output(source_path, fm, body, args):
    name = source_path.stem
    description = (fm.get("description") or "").strip()
    warnings = []
    if not description:
        warnings.append("description missing - OpenCode commands need a description; inserted a placeholder")
        description = f"Converted from {source_path.name}. TODO: write a real description."

    model, model_warn = map_model(fm.get("model"), args.provider, args.model_aliases)
    if model_warn:
        warnings.append(model_warn)

    if fm.get("argument-hint"):
        warnings.append("argument-hint has no OpenCode equivalent - dropped")

    out = ["---", f"description: {_yaml_str(description)}"]
    for key in ("agent", "variant", "subtask"):
        value = (fm.get(key) or "").strip()
        if value:
            out.append(f"{key}: {_yaml_str(value)}")
    if model:
        out.append(f"model: {model}")
    out.append("---")
    out.append("")
    src_sha = sha256_file(source_path)
    out.append(
        f"<!-- {GENERATED_MARKER} from {source_path.as_posix()} (source sha256 {src_sha[:12]}) on {_now()}. "
        f"Do not edit by hand - edit the canonical source and re-run sync_commands.py. -->"
    )
    out.append("")
    out.append(body.strip())
    out.append("")
    return name, "\n".join(out), warnings, src_sha


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="Claude command .md files, or directories to scan")
    ap.add_argument("--out-dir", default=".opencode/command", help="output directory (default: .opencode/command)")
    ap.add_argument("--provider", default="anthropic", help="provider prefix for bare model ids")
    ap.add_argument("--model-map", help="JSON file overriding the model alias table")
    ap.add_argument("--manifest", default=".opencode-sync/manifest.json")
    ap.add_argument("--dry-run", action="store_true", help="print what would be written, write nothing")
    ap.add_argument("--strict", action="store_true", help="exit 2 if any conversion produced warnings")
    args = ap.parse_args()

    args.model_aliases = dict(MODEL_ALIASES)
    if args.model_map:
        args.model_aliases.update(json.loads(Path(args.model_map).read_text()))

    files = []
    for raw in args.inputs:
        p = Path(raw)
        if p.is_dir():
            files.extend(sorted(p.glob("**/*.md")))
        elif p.is_file():
            files.append(p)
        else:
            print(f"WARN: {p} not found - skipped", file=sys.stderr)

    if not files:
        print("ERROR: no command .md files resolved from the inputs", file=sys.stderr)
        return 1

    out_dir = Path(args.out_dir)
    manifest = load_manifest(args.manifest)
    any_warnings, failures = False, 0

    for src in files:
        text = src.read_text(encoding="utf-8", errors="replace")
        fm_lines, body = split_frontmatter(text)
        if fm_lines is None:
            print(f"SKIP {src}: no YAML frontmatter found", file=sys.stderr)
            failures += 1
            continue
        fm = parse_frontmatter(fm_lines)
        name, output, warnings, src_sha = build_output(src, fm, body, args)
        dest = out_dir / f"{name}.md"

        print(f"{src} -> {dest}" + (f"  [{len(warnings)} warning(s)]" if warnings else ""))
        for w in warnings:
            print(f"  - {w}")
        if warnings:
            any_warnings = True

        if not args.dry_run:
            out_dir.mkdir(parents=True, exist_ok=True)
            dest.write_text(output, encoding="utf-8")
            manifest["generated"][dest.as_posix()] = {
                "source": src.as_posix(),
                "source_sha256": src_sha,
                "generated_sha256": sha256_text(output),
                "generated_at": _now(),
                "warnings": warnings,
            }

    if not args.dry_run and files:
        Path(args.manifest).parent.mkdir(parents=True, exist_ok=True)
        Path(args.manifest).write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"manifest updated: {args.manifest}")

    if failures:
        return 1
    if any_warnings and args.strict:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
